<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$orderHelper = $this->helper('Webkul\Marketplace\Helper\Orders');
$isPartner = $helper->isSeller();
if($isPartner == 1){
	$order_id = $this->getRequest()->getParam('order_id');

	$creditmemo_id = $this->getRequest()->getParam('creditmemo_id');

	$order = $block->getOrder();

	$creditmemo = $block->getCreditmemo();

	$paymentCode = '';
	$payment_method = '';
    if($order->getPayment()){
		$paymentCode = $order->getPayment()->getMethod();
		$payment_method = $order->getPayment()->getMethodInstance()->getTitle();
	}
	$creditmemo_status = '';
	if($creditmemo->getState()==1){
		$creditmemo_status = __('Pending');
	}else if($creditmemo->getState()==2){
		$creditmemo_status = __('Refunded');
	}else if($creditmemo->getState()==3){
		$creditmemo_status = __('Canceled');
	}
    $marketplace_orders = $block->getSellerOrderInfo($order_id);
	if(count($marketplace_orders)){	?>
		<div class="wk-mp-design">
			<div class="fieldset wk-mp-fieldset">
				<div class="page-title-wrapper">
				    <h1 class="page-title">
				        <span data-ui-id="page-title-wrapper" class="base">
				        	<?php echo __('Creditmemo #%1', $creditmemo->getIncrementId()) ?>
				        </span>
				    </h1>
				    <span class="order-status"><?php echo $creditmemo_status?></span>
					<div class="order-date">
					    <?php echo __('<span class="label">Order Date:</span> %1', '<date>' . $block->formatDate($creditmemo->getCreatedAt(),\IntlDateFormatter::MEDIUM, true, $block->getTimezoneForStore($order->getStore())) . '</date>') ?>
					</div>
					<div class="actions-toolbar order-actions-toolbar">
						<div class="actions">
							<a href="<?php echo $block->getUrl('marketplace/order_creditmemo/email', ['order_id'=>$order_id,'creditmemo_id'=>$creditmemo_id, '_secure' => $this->getRequest()->isSecure()])?>" onclick="return confirm('<?php echo __("Are you sure you want to send credit memo email to customer?") ?>')" class="action">
								<button class="button wk-mp-btn" title="<?php echo __('Send Email To Customer') ?>" type="button">
									<span><span><?php echo __('Send Email') ?></span></span>
								</button>
							</a>
							<a href="<?php echo $block->getUrl('marketplace/order_creditmemo/printpdf', ['order_id'=>$order_id,'creditmemo_id'=>$creditmemo_id, '_secure' => $this->getRequest()->isSecure()]);?>" class="action">
								<button class="button wk-mp-btn" title="<?php echo __('Print') ?>">
									<span><span><?php echo __('Print') ?></span></span>
								</button>
							</a>
					    </div>
					</div>
				</div>
				<div class="block block-order-details-view">
				    <div class="block-title">
				        <strong><?php echo __('Order Information') ?></strong>
				    </div>
				    <div class="block-content">
			            <div class="box-content">
			            	<div class="box wk-box">
					            <strong class="box-title wk-order-info-title">
					                <a href="<?php echo $block->getUrl('marketplace/order/view', ['id'=>$order_id, '_secure' => $this->getRequest()->isSecure()]);?>">
										<?php echo __('Order # %1',$order->getIncrementId()) ?>
									</a>
					            </strong>
					            <div class="box-content">
					                <div class="wk-row">
										<span class="label"><?php echo __('Order Status')?> : </span>
										<span class="value"><?php echo ucfirst($order->getStatus()); ?></span>
									</div>
									<div class="wk-row">
										<span class="label"><?php echo __('Order Date')?> : </span>
										<span class="value"><?php echo $block->formatDate($order->getCreatedAt(),\IntlDateFormatter::MEDIUM, true, $block->getTimezoneForStore($order->getStore())); ?></span>
									</div>
					            </div>
					        </div>
					        <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
				            	<div class="box wk-box">
						            <strong class="box-title"><span><?php echo __('Buyer Information') ?></span></strong>
						            <div class="box-content">
						                <div class="box wk-box">
							                <div class="wk-row">
												<span class="label"><?php echo __('Customer Name')?> : </span>
												<span class="value"><?php echo $order->getCustomerName(); ?></span>
											</div>
											<div class="wk-row">
												<span class="label"><?php echo __('Email')?> : </span>
												<span class="value"><?php echo $order->getCustomerEmail(); ?></span>
											</div>
										</div>
						            </div>
						        </div>
					        <?php } ?>
			            </div>
				    </div>
				</div>
				<?php if ($helper->getSellerProfileDisplayFlag()) { ?>
					<div class="block block-order-details-view">
					    <div class="block-title">
					        <strong><?php echo __('Address Information') ?></strong>
					    </div>
					    <div class="block-content">
				            <div class="box-content">
				            	<div class="box box-order-billing-address wk-box">
						            <strong class="box-title">
						                <span><?php echo __('Billing Address') ?></span>
						            </strong>
						            <div class="box-content">
						                <address><?php echo $block->getFormattedAddress($order->getBillingAddress()); ?></address>
						            </div>
						        </div>
				            	<?php if ($block->isOrderCanShip($order)): ?>
					            	<div class="box box-order-shipping-address wk-box">
							            <strong class="box-title"><span><?php echo __('Shipping Address') ?></span></strong>
							            <div class="box-content">
							                <address><?php echo $block->getFormattedAddress($order->getShippingAddress()); ?></address>
							            </div>
							        </div>
								<?php endif; ?>
				            </div>
					    </div>
					</div>
				<?php } ?>
				<div class="block block-order-details-view">
				    <div class="block-title">
				        <strong><?php echo __('Payment & Shipping Method') ?></strong>
				    </div>
				    <div class="block-content">
				        <div class="box box-order-billing-method wk-box">
				            <strong class="box-title">
				                <span><?php echo __('Payment Information') ?></span>
				            </strong>
				            <div class="box-content">
				                <?php echo $payment_method; ?>
				            </div>
				        </div>
					    <?php if ($block->isOrderCanShip($order)): ?>
					        <div class="box box-order-shipping-method wk-box">
					            <strong class="box-title">
					                <span><?php echo __('Shipping and Tracking Information') ?></span>
					            </strong>
					            <div class="box-content">
						            <?php if ($order->getShippingDescription()): ?>
						                <?php echo $block->escapeHtml($order->getShippingDescription()) ?>
						            <?php else: ?>
						                <?php echo __('No shipping information available'); ?>
						            <?php endif; ?>
					            </div>
					        </div>
					    <?php endif; ?>
				    </div>
				</div>
				<div class="block block-order-details-view wk-order-title-block">
				    <div class="block-title">
				        <strong><?php echo __('Items Refunded') ?></strong>
				    </div>
				</div>
				<div class="order-details-items ordered">
				    <div class="order-title">
				        <strong><?php echo __('Items Refunded') ?></strong>
				    </div>
				    <div class="table-wrapper order-items">
					    <table class="data table table-order-items creditmemo" id="my-orders-table" summary="<?php echo __('Items Refunded') ?>">
					        <caption class="table-caption"><?php echo __('Items Refunded') ?></caption>
					        <thead>
					            <tr>
					                <th class="col name"><?php echo __('Product Name') ?></th>
					                <th class="col price"><?php echo __('Price') ?></th>
					                <th class="col qty"><?php echo __('Qty') ?></th>
					                <th class="col price"><?php echo __('Subtotal') ?></th>
						            <?php
						            if($paymentCode == 'mpcashondelivery'){?>
						            	<th class="col price"><?php echo __('COD Charges') ?></th>
						            <?php
						            } ?>
						            <th class="col price"><?php echo __('Tax Amount') ?></th>
						            <th class="col price"><?php echo __('Discount Amount') ?></th>
						            <th class="col price"><?php echo __('Row Total') ?></th>
					            </tr>
					        </thead>
					        <?php
					        $_items = $order->getItemsCollection();
					        $i = 0;
						    $_count = $_items->count();
						    $subtotal = 0;
						    $vendor_subtotal =0;
						    $totaltax = 0;
						    $admin_subtotal =0;
						    $shippingamount = 0;
							$couponamount = 0;
						    $codcharges_total = 0;
						    $creditmemo_items = $block->getCreditmemoItemsCollection($creditmemo_id);

					    	foreach ($creditmemo_items as $_item) {
						        foreach ($_items as $_ordereditem) {
									if ($_ordereditem->getProductType()!='bundle') {
										if($_item->getOrderItemId() != $_ordereditem->getItemId()){
											continue;
										}
										$row_total = 0;
										$available_seller_item = 0;
										$shippingcharges = 0;
										$couponcharges = 0;
										$itemPrice = 0;
										$seller_item_cost = 0;
										$totaltax_peritem = 0;
										$codcharges_peritem = 0;
										$seller_item_commission = 0;
										$orderid = $order_id;

										$seller_orderslist = $block->getSellerOrdersList($orderid,$_item->getProductId(),$_item->getOrderItemId());
										foreach($seller_orderslist as $seller_item){
											$parentitem_falg = 0;
											$available_seller_item = 1;
											$totalamount = $seller_item->getTotalAmount();
											$seller_item_cost = $seller_item->getActualSellerAmount();
											$seller_item_commission = $seller_item->getTotalCommission();
											$shippingcharges = $seller_item->getShippingCharges();
											$couponcharges = $seller_item->getAppliedCouponAmount();
											$itemPrice = $seller_item->getMageproPrice();
											$totaltax_peritem = $seller_item->getTotalTax();
											if($paymentCode=='mpcashondelivery'){
												$codcharges_peritem = $seller_item->getCodCharges();
											}
										}
										if ($available_seller_item == 1) {
											$i++;
											$seller_item_qty = $_item->getQty();
											$row_total=$itemPrice*$seller_item_qty;
											$vendor_subtotal=$vendor_subtotal+$seller_item_cost;
											$subtotal=$subtotal+$row_total;
											$admin_subtotal = $admin_subtotal +$seller_item_commission;
											$totaltax=$totaltax+$totaltax_peritem;
											$codcharges_total=$codcharges_total+$codcharges_peritem;
											$shippingamount = $shippingamount+$shippingcharges;
											$couponamount = $couponamount+$couponcharges;

											$result = array();
											if ($options = $_ordereditem->getProductOptions()) {
												if (isset($options['options'])) {
													$result = array_merge($result, $options['options']);
												}
												if (isset($options['additional_options'])) {
													$result = array_merge($result, $options['additional_options']);
												}
												if (isset($options['attributes_info'])) {
													$result = array_merge($result, $options['attributes_info']);
												}
											} ?>
								        	<?php if ($_ordereditem->getParentItem()) continue; ?>
											<tbody>
												<tr class="border" id="order-item-row-<?php echo $_ordereditem->getId() ?>">
													<?php
													if($_ordereditem->getProductType()=='downloadable'){ ?>
														<td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
													        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
													        <?php if ($_options = $block->getItemOptions()): ?>
													            <dl class="item-options links">
													                <?php foreach ($_options as $_option) : ?>
													                    <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
													                    <?php if (!$block->getPrintStatus()): ?>
																									<?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
																									<dd>
																											<?php if (isset($_formatedOptionValue['full_view'])): ?>
																													<?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
																											<?php else: ?>
																													<?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
																											<?php endif; ?>
																									</dd>
													                    <?php else: ?>
													                        <dd><?php echo $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
													                    <?php endif; ?>
													                <?php endforeach; ?>
													            </dl>
													        <?php endif; ?>
													        <?php /* downloadable */?>
													        <?php if ($links = $block->getDownloadableLinks($_ordereditem->getId())): ?>
													            <dl class="item-options links">
													                <dt><?php /* @escapeNotVerified */ echo $block->getLinksTitle($_ordereditem->getId()) ?></dt>
													                <?php foreach ($links->getPurchasedItems() as $link): ?>
													                    <dd><?php echo $block->escapeHtml($link->getLinkTitle()); ?></dd>
													                <?php endforeach; ?>
													            </dl>
													        <?php endif; ?>
													        <?php /* EOF downloadable */?>

													        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
													        <?php if ($addInfoBlock) :?>
													            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
													        <?php endif; ?>
													        <?php echo $block->escapeHtml($_item->getDescription()) ?>
													    </td>
													<?php
													}else{ ?>
														<td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
															<strong class="product name product-item-name"><?php echo $block->escapeHtml($_ordereditem->getName()) ?></strong>
															<?php if($_options = $result): ?>
														        <dl class="item-options">
														        <?php foreach ($_options as $_option) : ?>
														            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
														            <?php if (!$block->getPrintStatus()): ?>
																						<?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
																						<dd>
																								<?php if (isset($_formatedOptionValue['full_view'])): ?>
																										<?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
																								<?php else: ?>
																										<?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
																								<?php endif; ?>
																						</dd>
														            <?php else: ?>
														                <dd>
														                    <?php echo nl2br($block->escapeHtml( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) )) ?>
														                </dd>
														            <?php endif; ?>
														        <?php endforeach; ?>
														        </dl>
													        <?php endif; ?>
														</td>
													<?php
													} ?>
													<td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
														<span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
														    <span class="cart-price">
														        <?php echo $order->formatPrice($_item->getPrice()); ?>
														    </span>
														</span>
													</td>
													<td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
										                <?php echo intval($_item->getQty()); ?>
													</td>
													<td class="col price" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>"><?php echo $order->formatPrice($_item->getRowTotal());?></td>
													<?php
										            if($paymentCode == 'mpcashondelivery'){?>
										            	<td class="col price" data-th="<?php echo $block->escapeHtml(__('COD Charges')) ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $codcharges_peritem));?></td>
										            <?php
										            } ?>
													<td class="col price" data-th="<?php echo $block->escapeHtml(__('Tax Total')); ?>"><?php echo $order->formatPrice($_item->getTaxAmount());?></td>
													<td class="col price" data-th="<?php echo $block->escapeHtml(__('Discount Total')); ?>"><?php /* @escapeNotVerified */ echo $order->formatPrice(-$_item->getDiscountAmount()) ?></td>
													<td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Row Total')); ?>">
														<?php echo $order->formatPrice(($_item->getRowTotal()+$_item->getTaxAmount()+$block->getOrderedPricebyorder($order, $codcharges_peritem))-$_item->getDiscountAmount());?>
													</td>
												</tr>
											</tbody>
											<?php
										}
									} else {
								        // for bundle product
								        if($_ordereditem->getChildrenItems()){
								        	$bundleitems = array_merge(array($_ordereditem), $_ordereditem->getChildrenItems());
								        }else{
								        	$bundleitems = array($_ordereditem);
								        }
								        $_count = count ($bundleitems);
								        $_index = 0;
								        $_prevOptionId = '';
										?>
										<?php foreach ($bundleitems as $_bundleitem): ?>
											<?php
											if($_item->getOrderItemId() != $_bundleitem->getItemId()){
												continue;
											}
											?>
											<?php $attributes_option = $block->getSelectionAttribute($_bundleitem); ?>
											<?php if ($_bundleitem->getParentItem()): ?>
												<?php $attributes = $attributes_option ?>
												<?php if ($_prevOptionId != $attributes['option_id']): ?>
												<tr class="options-label">
													<td class="col label" colspan="8" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
														<?php echo $attributes['option_label'] ?>
													</td>
												</tr>
												<?php $_prevOptionId = $attributes['option_id'] ?>
												<?php endif; ?>
											<?php endif; ?>
											<tr<?php echo (++$_index==$_count)?' class="border bundle"':' class="bundle"' ?> id="order-item-row-<?php echo $_bundleitem->getId() ?>">
												<?php 
												if (!$_bundleitem->getParentItem()){?>
													<td><h3 class="product-name"><?php echo $block->escapeHtml($_bundleitem->getName()) ?></h3></td>
													<td class="col price" data-rwd-label="<?php echo __('Price') ?>">
														<span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
															<?php echo $order->formatPrice($_item->getPrice());?>
														</span>
													</td>
													<td class="lin-hide">&nbsp;</td>
													<td class="lin-hide">&nbsp;</td>
													<td class="lin-hide">&nbsp;</td>
													<td class="lin-hide">&nbsp;</td>
												<?php
												} else { ?>
													<?php
													if ($_bundleitem->getQtyRefunded() == 0) {
														continue;
													}
													$row_total = 0;
													$available_seller_item = 0;
													$shippingcharges = 0;
													$couponcharges = 0;
													$itemPrice = 0;
													$seller_item_cost = 0;
													$totaltax_peritem = 0;
													$codcharges_peritem = 0;
													$seller_item_commission = 0;
													$orderid = $order_id;
													$seller_orderslist = $block->getSellerOrdersList(
														$orderid, $_bundleitem->getProductId(), $_bundleitem->getItemId()
													);
													foreach($seller_orderslist as $seller_item){
														$parentitem_falg = 0;
														$available_seller_item = 1;
														$totalamount = $seller_item->getTotalAmount();
														$seller_item_cost = $seller_item->getActualSellerAmount();
														$seller_item_commission = $seller_item->getTotalCommission();
														$shippingcharges = $seller_item->getShippingCharges();
														$couponcharges = $seller_item->getAppliedCouponAmount();
														$itemPrice = $seller_item->getMageproPrice();
														$totaltax_peritem = $seller_item->getTotalTax();
														if($paymentCode=='mpcashondelivery'){
															$codcharges_peritem = $seller_item->getCodCharges();
														}
													}
													$i++;
													$seller_item_qty = $_bundleitem->getQtyRefunded();
													$row_total=$itemPrice*$seller_item_qty;
													$vendor_subtotal=$vendor_subtotal+$seller_item_cost;
													$subtotal=$subtotal+$row_total;
													$admin_subtotal = $admin_subtotal +$seller_item_commission;
													$totaltax=$totaltax+$totaltax_peritem;
													$codcharges_total=$codcharges_total+$codcharges_peritem;
													$shippingamount = $shippingamount+$shippingcharges;
													$couponamount = $couponamount+$couponcharges;
													?>
													<td class="col value" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
														<?php echo $block->getValueHtml($_bundleitem)?>
														<?php $addInfoBlock = $block->getOrderItemAdditionalInfoBlock(); ?>
														<?php if ($addInfoBlock): ?>
															<?php echo $addInfoBlock->setItem($_bundleitem)->toHtml() ?>
														<?php endif;?>
													</td>
													<td class="col price" data-rwd-label="<?php echo __('Price') ?>"><?php echo $order->formatPrice($_bundleitem->getPrice());?>
													</td>
													<td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
														<?php echo intval($_item->getQty()); ?>
													</td>
													<td class="col price" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>"><?php echo $order->formatPrice($_item->getRowTotal());?></td>
													<?php
													if($paymentCode == 'mpcashondelivery'){?>
														<td class="col price" data-th="<?php echo $block->escapeHtml(__('COD Charges')) ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $codcharges_peritem));?></td>
													<?php
													} ?>
													<td class="col price" data-th="<?php echo $block->escapeHtml(__('Tax Total')); ?>"><?php echo $order->formatPrice($_item->getTaxAmount());?></td>
													<td class="col price" data-th="<?php echo $block->escapeHtml(__('Discount Total')); ?>"><?php /* @escapeNotVerified */ echo $order->formatPrice(-$_item->getDiscountAmount()) ?></td>
													<td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Row Total')); ?>">
														<?php echo $order->formatPrice(($_item->getRowTotal()+$_item->getTaxAmount()+$block->getOrderedPricebyorder($order, $codcharges_peritem))-$_item->getDiscountAmount());?>
													</td>
												<?php
												}?>
											</tr>
										<?php endforeach; ?>
										<?php
									}
						        }
						    } ?>
					        <?php
						    foreach($marketplace_orders as $tracking){
								$shippingamount=$tracking->getShippingCharges();
							}
				            if($paymentCode == 'mpcashondelivery'){
					        	$count_td = 7;
					       	}else{
					       		$count_td = 6;
					       	} ?>
					        <tfoot>
							    <tr class="subtotal">
							        <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
							            <?php echo __('Subtotal')?>
							        </th>
							        <td data-th="<?php echo __('Subtotal')?>" class="amount">
							        	<?php echo $order->formatPrice($creditmemo->getSubtotal()); ?>
							        </td>
							    </tr>
							    <tr class="subtotal">
							        <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
							            <?php echo __('Discount')?>
							        </th>
							        <td data-th="<?php echo __('Discount')?>" class="amount">
							        	<?php echo $order->formatPrice($creditmemo->getDiscountAmount()); ?>
							        </td>
							    </tr>
							    <tr class="subtotal">
							        <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
							            <?php echo __('Total Tax')?>
							        </th>
							        <td data-th="<?php echo __('Total Tax')?>" class="amount">
							        	<?php echo $order->formatPrice($creditmemo->getTaxAmount()); ?>
							        </td>
							    </tr>
							    <tr class="subtotal">
							        <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
							            <?php echo __('Shipping & Handling')?>
							        </th>
							        <td data-th="<?php echo __('Shipping & Handling')?>" class="amount">
							        	<?php echo $order->formatPrice($creditmemo->getShippingAmount()); ?>
							        </td>
							    </tr>
							    <?php
					            if($paymentCode == 'mpcashondelivery'){ ?>
							    	<tr class="subtotal">
							    		<th colspan="<?php echo $count_td ?>" class="mark" scope="row">
								            <?php echo __('Total COD Charges')?>
								        </th>
								        <td data-th="<?php echo __('Total COD Charges')?>" class="amount">
								        	0
								        </td>
							    	</tr>
							    <?php
							    }?>
							    <tr class="subtotal">
							        <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
							            <?php echo __('Adjustment Refund')?>
							        </th>
							        <td data-th="<?php echo __('Adjustment Refund')?>" class="amount">
							        	<?php echo $order->formatPrice($creditmemo->getAdjustmentPositive()); ?>
							        </td>
							    </tr>
							    <tr class="subtotal">
							        <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
							            <?php echo __('Adjustment Fee')?>
							        </th>
							        <td data-th="<?php echo __('Adjustment Fee')?>" class="amount">
							        	<?php echo $order->formatPrice($creditmemo->getAdjustmentNegative()); ?>
							        </td>
							    </tr>
							    <tr class="subtotal">
							        <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
							            <strong><?php echo __('Grand Total')?></strong>
							        </th>
							        <td data-th="<?php echo __('Grand Total')?>" class="amount">
							        	<strong><?php echo $order->formatPrice($creditmemo->getGrandTotal()); ?></strong>
							        </td>
							    </tr>
						    </tfoot>
					    </table>
					</div>
			    </div>
			</div>
		</div>
		<div class="buttons-set">
			<p class="back-link">
				<a href="<?php echo $block->getUrl('marketplace/order/history', ['_secure' => $this->getRequest()->isSecure()]);?>" class="left">&laquo; <?php echo __('Back To My Orders') ?></a>
			</p>
		</div>
		<?php
	}
}else{ ?>
	<h2 class="wk-mp-error_msg">
		<?php echo __("To Become Seller Please Contact to Admin."); ?>
	</h2>
	<?php
} ?>
